# Generated by Django 2.0.4 on 2018-04-18 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180418_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='pub_date',
        ),
    ]
