# Generated by Django 2.0.4 on 2018-04-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180418_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathersearch',
            name='celsius',
            field=models.FloatField(),
        ),
    ]
